### ISSUE TITLE
Doku: wie bringe ich Gluon auf meinen FF-Router

### ISSUE THREAD

**Issue by whallmann** [freifunk-mwu/technik-meta#15]
Ich fange das Thema mal an und trage nochmal kurz zusammen, was bisher das Resüme war zum Thema Texte anpassen für den Gluon-Wizard die der Benutzer als Info sieht:
* Nur wenige Texte lassen sich über die Site-conf anpassen
* Mehr zu ändern wäre aufwändig und nicht nachhaltig
* Verhalten und Vorbelegung von Feldern und Checkboxen ist ebenso kaum möglich
* Für unbedingt notwendige Änderungswünsche sollte ein Ticket bei Gluon-Entwicklern aufgemacht werden.

**Mein Vorschlag daraus resultierend:**
- Wir lassen die Texte so wie sie sind. Sie sind ja grundsätzlich ok.
- Ein Schwerpunkt für Informationen dazu, sollte die Beschreibung sein, die eher ein Nachschlagewerk zum Wizard dar stellt.

**Bedarf an Beschreibungen:**
a) Wie stelle ich meinen bisherigen FF-Router um
b) Was man zum Gluon-Konfig-Wizard wissen sollte

Punkt a) dürfte klar sein. Aber beim Punkt b) frage ich mich wie wir diesen erreichbar machen?
Ich frage deshalb, weil ich mir denke, dass man vor dem Wizard sitzt und ggf. was wissen will dazu. Wie komme ich am einfachsten an erklärende Texte? z.B. ala einer kontextsensitiven Hilfe.

**Die Idee:**
Gibt es die Möglichkeit über einen internen Link im Image eine html Datei anzeigen zu lassen? Dann könnte die Hilfe immer aktuell direkt mit integriert werden. Benötigt ja nicht viel Platz speichermäßig.

Wenn das nicht gehen sollte muss ganz profan eine Wiki-Seite dafür herhalten.

Damit würde ich alsbald beginnen wollen. Hardcopies liegen hier schon parat und den bisherigen Link im Wiki für die Umstellungs Anleitung für bisherige FF Router finde ich bestimmt auch noch wieder.

Ich freue mich auf eure Kommentare

**Comment by kokel** [comment]
@whallmann Die Flash Anleitung ist doch nun fertig und auf der Homepage. Kann dieses Issue geschlossen werden?

**Comment by whallmann** [comment]
jo klar. is closed.

mit freundlichen Grüßen

Wolfgang Hallmann
Frh-von-Wallbrunn-Str. 42
55288 Partenheim
---
Wenn Sie mir eine *verschlüsselte E-Mail* senden möchten,
finden Sie meinen öffentlichen PGP-Schlüssel unter
http://www.familie-hallmann.info/Public_key.txt
(PGP-ID: 2048R/A4A27463 erstellt am 20.10.2013)


2015-03-01 16:53 GMT+01:00 Tobias Hachmer <notifications@github.com>:

**Comment by spookey** [comment]
Wie schaut es aus mit den Wikiseiten zum Thema? Ich denke im Laufe der Zeit kann es subtile Änderungen geben, und somit driften beide Anleitungen auseinander?
Können/Wollen/Sollen die Seiten weg, und wenn ja, welche genau?

**Comment by kokel** [comment]
Vote für: Raus aus dem Wiki! Wozu zwei Versionen? Weg damit!

**Comment by whallmann** [comment]
Im Prinzip stimme ich zu mit dem "weg aus dem Wiki".  Dumm nur das es da
noch den Teil gibt, der Freifunk-Images auf Gluon bringt. Auf der Homepage
steht nur wie man "frische" Geräte auf Gluon bekommt.
Den Teil würde ich erst noch ein wenig drinne lassen, bis die
Übergangsphase abgeschlossen ist.
Alternativ könnte ich im Wiki den Teil raus nehmen der "Neugeräte"
behandelt und auf die HP verweisen.
Bei evtl. nachträglichen Anpassungen kann ich das aber gerne noch diese
Zeit gleich halten.

Meinungen?
​

**Comment by kokel** [comment]
Die Anleitung für das Flashen von neuen Geräten + Einrichtung von Gluon kann aus dem Wiki verschwinden. Wenn es die Anleitung wie man legacy Geräte (also stock openwrt) auf Gluon bringt nur im Wiki existiert auch gut, die kann ja für die paar Monate noch weiterleben...

**Comment by ka-ba** [comment]
Sehe ich ebenso:
Anleitung für ladenfrische Geräte (nur!) im Web, Anleitung für bereits OpenWRT-infizierte Geräte (nur!) im Wiki und jeweils Verweise aufeinander.

**Comment by ungenannter** [comment]
Was haltet ihr von der Idee ggf. auch Partnerlinks einzubinden? 
Sprich in dem Abschnitt "Router besorgen" einen Link zu einem Online Shop der TPlinks verkauft?

 Z.B. haben Reichelt, Conrad und Amazon ein Partnerprogramm welches wir als zusätzliche Geldquelle nutzen könnten.

https://partnernet.amazon.de/
https://www.affili.net/de/partnerprogramme/computer-hard-software/hardware-zubehor/reichelt-elektronik

**Comment by spookey** [comment]
Absolut gar nichts.

**Comment by kokel** [comment]
@ungenannter Das hat m.M.n nicht direkt mit diesem Issue zu tun. Das klären wir Offline.
@whallmann Schließt du dieses Issue wenn du fertig bist, bitte?

**Comment by whallmann** [comment]
So die Beschreibungen zum Um- und Einstieg sind getrennt und entsprechend im Wiki und auf der HP eingebunden. Fertig.
