### ISSUE TITLE
DNS Einträge für "user.ff*.org"

### ISSUE THREAD

**Issue by Klexx** [freifunk-mwu/technik-meta#20]
Es gibt wohl noch keinen Prozess um Nutzern DNS (ggf. DHCP ?) Einträge zuzuweisen. Wie sollen diese beantragt und umgesetzt werden?

**Comment by kokel** [comment]
Voraussetzung für einen DNS Eintrag wird zunächst eine fest IP Adresse sein, da haben wir auch noch keinen Prozess. Dynamisches DNS über DHCP ist in meinen Augen schon mal disqualifiziert, weil wir dafür MAC Adressen bzw. DUIDs speichern müssen (dauerhaft).

**Comment by ka-ba** [comment]
Seitenbemerkung: IP-Reservierungsprozess benötigen wir auch für die Richtfunkgeräte des Backbone - dafür gibt's aktuell eine kleine Liste im Wiki.

**Comment by kokel** [comment]
Ich habe für den Prozess IP-Adresse sowie DNS Namen beantragen mal ein IPAM aufgesetzt:

Software: http://phpipam.net/
URL: http://[fd56:b4dc:4b1e:0:5054:ff:fe79:fded]/phpipam

User: admin
PW: ipamadmin

Mal als Spielwiese um zu schauen ob das was ist. User ohne Login können IP Adressen beantragen, wir könenn unsere Subnetze und Geräte dort verwalten, etc.

Schaut es euch mal an.

**Comment by ka-ba** [comment]
Sieht ganz schick aus!
Wie funktioniert denn das hinten dran? (Dazu sehe ich nicht direkt was auf der web site.) Hat das direkte Anbindungen an bind und dhcpd? Oder ist das die reine Verwaltung und man muss's dann noch zu Fuß technisch umsetzen?

aside: Wollen wir für v6 nicht eine ähnliche Netzaufteilung, wie für v4? Geht das mit der automagischen Adressvergabe dann noch?

**Comment by kokel** [comment]
Das unterhält sich nicht mit bind und dhcpd. das einzige was es kann ist dieser host check (ping). Ist also eher rein statischer Natur Aber wenn es sich z.B. mit dhcpd unterhalten würde hätten wir auch wieder zu viel Infos über z.B. Clients.

Das IPAM ist zunächst sehr statisch. Bietet aber selbst ne API an, die ich mir aber auch nicht genauer angeschaut habe. Das beste ist halt momentan die Möglichkeit IP Adressen zu beantragen. Das konnte ich bei anderen IPAMs nun nicht so schnell finden. Aber wenn jemand ein IPAM kennt was noch mehr Features kann und vor allem auch das Beantragen von IPs (DNS) ohne Login wäre super!

Ich schau mal nach der Netzaufteilung für v6, da das IPAM sehr statisch ist könnte das klappen. Aber das kleinste Subnetz bei v6 ist nunmal /64 (Ausnahme Inter-Router Links, siehe RFC 6164). Der Interface-Identifier, den sich die Clients erzeugen ist ja genau für diese größe standardisiert.
