### ISSUE TITLE
tincd auf hinterschinken erneut gestorben - auto-restarts?

### ISSUE THREAD

**Issue by ka-ba** [freifunk-mwu/technik-meta#22]
Früher schon öfter beobachtet, damals immer ohne Hinweise.
Heute ist wieder der tincd auf dem hinterschinken gestorben. Ich kann nicht sagen, ob das nicht auch auf den anderen gates regelmäßig vorkommt!?
Diese mal gibt das syslog etwas her; die letzten zewi inc-Zeilen:
```
Jan  3 22:40:31 hinterschinken tinc.icVPN[3128]: Got fatal signal 11 (Segmentation fault)
Jan  3 22:40:31 hinterschinken tinc.icVPN[3128]: Trying to re-execute in 5 seconds...
```
... das re.execute scheint nicht gefunxt zu haben.

Sollten wir noch einen cron-job aufsetzen, der unsere gewünschten Dienste regelmäßig prüft und ggfs. automagisiert neu startet? Falls ja, wie verhindern wir den Neustart, wenn wir gerade etwas dran schrauben?

**Comment by spookey** [comment]
Hallo,

> Sollten wir noch einen cron-job aufsetzen, der unsere gewünschten Dienste regelmäßig prüft und ggfs. automagisiert neu startet?

Finde nicht dass das eine gute Idee ist, den größten Nachteil nennst du selbst:

> Falls ja, wie verhindern wir den Neustart, wenn wir gerade etwas dran schrauben?

Klar lässt sich da was frickeln, jedoch vergisst man dann genauso häufig den cronjob auszukommentieren, wie das mit dem jeweiligen backend oder map-script passiert.

Wäre das nicht ein schöner Anwendungsfall für unser Monitoring?

**Comment by ka-ba** [comment]
Ja, sehr gerne auch über's Monitoring! :+1:
Bietet sich da als Plattform die map-Maschine an? (Wofür sind die anderen neuen Server???)
Sollen wir das als issue anlegen?
Wer hat Lust, das aufzusetzen?
Können wir das backbone-Monitoring direkt integrieren (mit eigener BB-Admin-Gruppe)?

**Comment by kokel** [comment]
Der @knirps99 hat doch schon ein Observium sowie ein LibreNMS aufgesetzt. Aber zum Problem:
Ich war so frei und habe die aktuelle Version von tinc für Ubuntu Trusty paketiert und ins [Freifunk MWU PPA](https://launchpad.net/~freifunk-mwu/+archive/ubuntu/freifunk-ppa) geworfen. Ist schon wieder fast einen Monat her und seitdem gabs meines Wissens nach keine ähnliches Probleme mehr.

**Comment by ka-ba** [comment]
geschlossen zugunsten von: https://github.com/freifunk-mwu/technik-meta/issues/32
