### ISSUE TITLE
Karte: BB nodes gesondert kennzeichnen

### ISSUE THREAD

**Issue by ka-ba** [freifunk-mwu/technik-meta#23]
Moin!

Haben wir eine Möglichkeit, BB nodes in der Karte besonders zu kennzeichnen (ähnlich wie gateways)?

**Comment by spookey** [comment]
Wir nutzen ein ``aliases.json`` ähnlich der wie in https://github.com/ffnord/ffmap-backend/blob/master/aliases.json_sample

Bei uns steht halt sowas wie:

    {
        ...
       "02:00:0a:38:00:07" : {
          "name" : "Spinat",
          "vpn" : true,
          "firmware" : "Ubuntu",
          "hardware" : "x86"
       },
        ...
    }

Um einen neuen Typen von Nodes einzuführen müssen wir an die Software ran, wie aktuell unser Fork am Original dran ist, weiß ich nicht.

**Comment by kokel** [comment]
Die aliases.json wäre eine Möglichkeit. Aber sehr statisch. Mit der map an sich hat das erstmal nichts zu tun. Die BB Knoten müssten halt am besten was per Alfred announcen. Könnte man ein neues Feld für nehmen wie z.b. "devtype": [node|gateway|backbone]

Aber dafür müsste man die Firmware anpassen, einfach ein announce-script mehr. könnten wir z.b. über ein eigenes Paket machen zusammen mit einem config-mode Paket, damit es im config-mode konfigurierbar wird.

Die Karte dann anzupassen ist das kleinste Problem.

**Comment by ka-ba** [comment]
Die Menge der BB-nodes _wird_ eine verhältnismäßig statische Angelegenheit sein.

Wenn ich Eure beiden Kommentare zusammen nehme, klingt das doch total positiv. :wink: Vielleicht können wir die BB tatsächlich in die aliases.json aufnehmen *und* diesen devtype - ohne Änderung der FW - einführen? In der aliases setzen wir den devtype für gates und bb-nodes (und für srvr?), der default für alle anderen lautet halt "node". Geht das?
Graphisch: geht das, die BB-nodes gesondert zu layouten und die Verbindung zwischen zwei bb-nodes (nicht aber von bb-nodes zu anderen) auch irgendwie anders erscheinen zu lassen?

**Comment by spookey** [comment]
Habe heute mal in das Kartenbackend gesehen, und musste feststellen, dass der Rewrite gar nicht so aktiv betrieben wird/eingeschlafen ist, wie mir damals beschrieben wurde..

Denke, dass wir schon an den Code ins Karten-Backend ran können, denn das scheint mir die flexiblere Lösung im Gegensatz zur aliases.json

Jedoch: Ob wir direkt ein Alfred-Announce-Modul schreiben müssen, weiss ich noch nicht, vielleicht können wir die Backbone-Nodes gleich anhand anderer bereits vorhandener Merkmale ermitteln (Andere Netzwerk-Range, Routing)

Falls doch, so lass uns das Feld bitte nicht devtype nennen, das ist mir zu unspezifisch und es erschließt sich einem dritten nicht was eigentlich bezeichnet werden soll. Lass uns lieber was mit role oder group einführen.

Falls du ein ffmwu-packages.git anlegen möchtest - gerne, es sollte nur pro Community ein Branch angelegt werden, damit man die spezifischen Unterschiede Abbilden kann..

**Comment by kokel** [comment]
@spookey: der branch "rewrite" ist auch tot. Das richtige "rewrite" wurde im branch "dev" vollzogen. Das passt allerdings nicht zum Frontend, das muss auch noch angepasst werden.

"devtype" war auch nur ein Beispiel. "group" fände ich auch besser.

Wir können es mit dem paket auch erst lassen und die config auf den Backbone Knoten manuell machen, sind zwei Zeilen in /etc/config/gluon-node-info und ein einzeiliges announce script ( genau das was das Paket auch machen würde ;-))

@ka-ba: den Backbone nodes einen anders farbigen kringel zu verpassen ist sehr einfach. Die Mesh-Links anders farbig darzustellen wird mit Sicherheit schwieriger. Hab ich mir noch nicht angesehen.

**Comment by kokel** [comment]
Z.B. das hier würde ausreichen, damit ein gluon knoten was zusätzliches announced (manuell):

/etc/config/gluon-node-info
```
~# uci add gluon-node-info usage
~# uci set gluon-node-info.@usage[0].group=backbone
~# uci commit
```

/lib/gluon/announce/nodeinfo.d/group
```
return uci:get_first('gluon-node-info', 'usage', 'group')
```

Das ist alles und die node announced im datatype 158 "group: 'backbone'"

**Comment by ka-ba** [comment]
Hah, Ihr seid ja großartig! :+1: :grinning: 

Probiere das bei mir die Tage auch mal aus und schiebe dann M. & W. an, dass die das auf den zwei wirklichen bb-nodes setzen.
Wie bekomme ich das danach wieder weg? Vermutlich einfach `/lib/gluon/announce/nodeinfo.d/group` wieder löschen, richtig?

Hmm, Kringelfarbe? Die meisten sinnvollen Farben sind schon vergeben ... wie wäre es einfach mit schwarz? (*1)
Für die Links im BB sollte die Farbkodierung vielleicht erhalten bleiben - da möchte mensch auch die Qualität optisch erfassen können. Eine Form von Strichelung (aber verschieden von jener des VPN) wäre die Kür. Aber die gekennzeichneten Nodes sind auch schon mal super!

(*1) "aber schwarz ist doch gar keine Farbe" [Spliff?] - ja, ja, ich weiß :wink:

**Comment by kokel** [comment]
So, Backbone Knoten werden nun gesondert gekennzeichnet, wenn die über alfred `"group": "backbone"` announcen. Habs auch gleich für die Service Knoten mitgemacht.

**Comment by kokel** [comment]
Nun werden Backbone Links gesondert dargestellt. Habe die extra Kringel dann erstmal wieder entfernt, war doch ein wenig too fancy, oder?

Karten Backend: https://github.com/freifunk-mwu/ffmap-backend/commit/3c8d5df9c7fb233c66a0be31d199a3361859919a
Karten Frontend: https://github.com/freifunk-mwu/ffmap-d3/commit/1a9f6804c8c13322b5ea4469fe766a2fffe08989

**Comment by kokel** [comment]
Ich finde, das wir nur den wirklichen backbone geräten die gruppe backbone zusätzlich announcen lassen sollten. Auf den Geräten, die eine Verbindung zum Backbone aufbauen ist das nicht notwendig?!

**Comment by knirps99** [comment]
Coole nummer auf jeden fall ich hab den alfred kram mal auf dem
zahnklinik router gesetzt

kann man die gestrichelte Linie fuer die Backbone verbindung auch in
der Karte anzeigen ?

Gruesse
Moritz

**Comment by ka-ba** [comment]
Kokel, völlig richtig, so sehe ich's auch: nur echte BB-Nodes sollen das announcen. Dem Bell hatte ich das nur gegeben, um den Effekt mal zu sehen, bis Knirps es auf der UniMedizin aktiviert hat. Ich nehm's dann wieder raus!
(Dann ist allerdings erst mal nix mehr zu sehen; UniMed ist aktuell der einzige wirkliche BB-Node. Der farbige Rand hat Dir nicht gefallen?)

**Comment by kokel** [comment]
ka-ba, es reicht, wenn ein node sich als Backbone announced. Die Links zu diesem node werden dann dem link type Backbone zugewiesen. 

Joa, ich fand die Karte sah ein wenig überladen aus, kann aber auch an dem zusätzlichen Service Stroke gelegen haben. 

Soll ich es wieder mit rein nehmen? Was sagen die anderen? 

@knirps99: Die BB Links auf der geomap genauso darzustellen ist bestimmt auch möglich. Schau ich mir bei Gelegenheit mal an. Aber macht das Sinn? Da gibt es ja keine Legende...

**Comment by kokel** [comment]
Habe das mit der group/role gestern im gluon irc vorgestellt. Wurde für sinnvoll befunden. Allerdings wurde befunden statt `group` `role` zu benutzen. Der section name `usage` soll auch noch in was passenderes umbenannt werden, Vorschläge?

Ich werde mich dann mal daran versuchen, das in ein gluon Paket zu packen und einen PR vorbereiten.

**Comment by kokel** [comment]
So, gute Neuigkeiten! Das Paket zum Konfigurieren der Knoten Rolle im Config Mode (Expert) ist nun gemerged, ebenso wie die Erweiterungen des vorhandenen Pakets `gluon-node-info`, siehe die commits:

- Config-Mode Paket: https://github.com/freifunk-gluon/packages/commit/6804d871297d324fe45bfc5520c3be691b08469b
- Erweiterung von `gluon-node-info`: https://github.com/freifunk-gluon/packages/commit/547574d7da0077a593eeafb9aac4f6997e176580

Welche Rollen es ingesamt gibt legen wir in der site.conf fest:
```
  roles = {
    default = 'node',
    list = {
        node = 'Normaler Knoten',
        backbone = 'Backbone Knoten',
    },
  },
```
Per default hat jeder Knoten die Rolle `node`. Die Liste ist letztendlich nur für den config-mode interessant, da man dort in einem Dropdown Feld die Rolle auswählen kann.
Linker Wert = Key (Das, was in die Config geschrieben und announced wird)
Rechter Wert = Value (Prettyname zur Anzeige im Config-Mode)

Im Vergleich zum Workaround oben hat sich ein wenig was geändert. Die Config muss auf den Knoten (z.B. Backbone) nun so aussehen:

### Wo wird die Rolleninformation gespeichert?
`/etc/config/gluon-node-info`
```
config location
        .......

config owner
        ........

config system
        option role 'backbone'
```
Hier ist die config section `system` mit der `option` `role` hinzugekommen.

### Wie wird die Rolle über Alfred announced?
`/lib/gluon/announce/nodeinfo.d/system/role`
```
local role = uci:get_first('gluon-node-info', 'system', 'role', '')
if role ~= '' then
        return role
end
```
Das würde dann im Alfred Output ungefähr so aussehen:
```
    "system": {
      "role": "backbone"
    },

```
Ich werde die Änderungen dann in der site.conf und site.mk vornehmen.

**Comment by kokel** [comment]
@knirps99 Bitte die vorhandenen Backbone Knoten auf die neue Config umstellen. Die Karte passe ich dieses WE dann auch noch an. Die gesamte Config Section `gluon-node-info.usage` muss weg und dann wie hier beschrieben vorgehen: https://gist.github.com/kokel/f8910ddb188ad3ab459f

Ab gluon v2015.1 haben wir dann auch das neue Paket in unserer Firmware.
