### ISSUE TITLE
Keys Repo vom Mettigel

### ISSUE THREAD

**Issue by spookey** [freifunk-mwu/technik-meta#24]
Hallo,

das [Keys Repo vom Mettigel](http://github.com/freifunk-mwu/gluon-ffmz-keys) ist doch nun nicht mehr in Benutzung, oder?

Kann das weg, oder hat jemand irgendwelche Schätze darin verborgen, die man erhalten sollte?

**Comment by kokel** [comment]
Meine Meinung: Kann weg. Diejenigen, die dort einen Knoten hatten sollten sowieso `sysupgrade -n ` machen.

**Comment by kokel** [comment]
Nun kann das aber wirklich gelöscht werden. War genug Zeit da....

**Comment by ungenannter** [comment]
:+1:
