### ISSUE TITLE
Gluon-Gateway-Doku zu NTP

### ISSUE THREAD

**Issue by spookey** [freifunk-mwu/technik-meta#25]
Habe eben entdeckt, dass wir keinen Abschnitt zu NTP in unserer Doku hatten.

Beim anlegen fällt mir auf/wieder ein, dass wir damals&trade; Probleme hatten die Gateways gleichzeitig als Clients und als Server nur für die Mesh-Netzwerke zu betreiben, und etwas mit dem Routing gebastelt werden musste.

Wo schlägt sich das in der ``/etc/ntp.conf`` nieder, und fühlt sich jemand berufen den Abschnitt weiter auszubauen?
http://gluon-gateway-doku.readthedocs.org/de/latest/configuration/basics.html#ntp

**Comment by kokel** [comment]
Die ursprüngliche Idee war, dass der ntp Server nur aus dem freifunk Netz abfragbar sein sollte. Mit ntpd Bordmitteln sind meine versuche damals gescheitert. Ich kann es mir nochmal anschauen. Zur not ließe sich das auch über zwei einfache ipt[6]tables regeln lösen, die die Abfrage aus dem inet verhindern.

**Comment by kokel** [comment]
Also ich habe es mir nochmal angeschaut und es wieder nicht hinbekommen. Ega, was ich versuche, der ntp server ist hinterher nicht mehr in der Lage selbst seine Zeit von extern abzuholen. Wenn sich noch jemand versuchen will, gerne.
