### ISSUE TITLE
Aendern der dhcp range auf den Gates von /20 auf /22

### ISSUE THREAD

**Issue by knirps99** [freifunk-mwu/technik-meta#26]
Um platz im netzplan fuer ein weiteres Gate zu bekommen habe ich die Subnetzmasken der DHCP Ranges auf /22 umgestellt.

**Comment by ka-ba** [comment]
Wieso direkt auf 22 und nicht erst Mal auf 21???? Brauchen wir den nun frei gewordenen Platz für etwas?

**Comment by kokel** [comment]
Die Überlegung dahinter war, dass 1024 Clients pro Gate lange ausreicht. Ein Gate kann praktisch ja auch längst nicht den gesamten Traffic von 1024 Clients transferrieren, wenn alle ca. 1MBit/s machen würden. Wir brauchten einfach Platz für mind. 2 neue Gates.
