### ISSUE TITLE
Etherpad down

### ISSUE THREAD

**Issue by ungenannter** [freifunk-mwu/technik-meta#27]
Habe gegen 12:33 festgestellt, dass das etherpad down ist.

**Comment by kokel** [comment]
Gefixt, rennt wieder ...

**Comment by whallmann** [comment]
Danke dir... es wurde schon vermisst :-)
​

**Comment by ungenannter** [comment]
Kannst du uns sagen, was das Problem war und wie du er gelöst hast ?

**Comment by kokel** [comment]
Der Dienst lief einfach nicht, dann habe ich in der Uberspace Doku geschaut, wie man etherpad-lite ans laufen bringt und einen Dienst dafür einrichtet: https://wiki.uberspace.de/system:daemontools

Also:
```
cd ~/service
ln -s ~/etc/run-etherpad-lite etherpad-lite
svc -u ~/service/etherpad-lite
```

Und fertig ist die Kiste. Wenn man Plugins installieren möchte, dann:
```
cd ~/software/etherpad-lite
npm install <plugin-name>
svc -du ~/service/etherpad-lite
```
und fertig...
