### ISSUE TITLE
SSL für Webserver

### ISSUE THREAD

**Issue by Klexx** [freifunk-mwu/technik-meta#29]
Derzeit gibts es auf einigen Web-Servern kein ssl. Besonders stört mich das beim download der firmware (http://firmware.freifunk-mwu.de).
Ich finde, dass wir das nachrüsten sollten.

**Comment by ka-ba** [comment]
Können wir diesen Punkt hier im Zuge der aktuellen Cert-Neubeschaffung mit eintüten?

**Comment by ca-haddock** [comment]
Cert-Neubeschaffung ? Wo?
Wollen wir uns für die Beta von Let´s Encrypt  anmelden ?
https://docs.google.com/forms/d/15Ucm4A20y2rf9gySCTXD6yoLG6Tba7AwYgglV7CKHmM/viewform?c=0&w=1

**Comment by MAGICCC** [comment]
Nehmen die noch an? Habe mich am ersten Tag mal angemeldet, ne Mail bekommen aber noch nichts aufgesetzt :(
Afaik gibt es bald eine OpenBeta

**Comment by ca-haddock** [comment]
Mal versuchen ansonsten finde ich wosing https://buy.wosign.com/free/ gut.Certs für  3 Jahre free.
Oder Startssl https://www.startssl.com/, machen aber nur 1 Jahr für lau.

**Comment by ka-ba** [comment]
... vergl. Protokoll Admin-Treffen (im pad)

**Comment by ca-haddock** [comment]
ok startcom machen. Die nun 2 Jahre war mir neu.

**Comment by ka-ba** [comment]
... ich nehme an, diesen hier können wir mal langsam schließen!? ...

**Comment by kokel** [comment]
Der download von Firmware ist immernoch nur über http möglich ...

**Comment by jreinert** [comment]
Letsencrypt hab ich seit der beta auf mehreren Servern, auch auf der Arbeit, eingerichtet und tut super.

**Comment by MAGICCC** [comment]
Solange das Cert von StartSSL noch gültig ist, sehe ich keinen Grund auf LE zu gehen. Danach gerne, geht ja schnell mit certbot

**Comment by belzebub40k** [comment]
IMHO ist Certbot viel zu aufgebläht und ich hab immer wieder Probleme gehabt bei Updates.
Ich verwende auf meinen Servern [dehydrated](https://github.com/lukas2511/dehydrated) (letsencrypt.sh) welches das letsencrypt Protokoll als simples Shell-Script implementiert und als einzige Abhängigkeit `openssl` hat.

**Comment by kokel** [comment]
Hätte nichts dagegen auf LE zu wechseln. In den StartSSL Certs steht aktuell auch noch mein Name drin. Habe ich nichts gegen, aber schöner wäre dann doch LE. Müssen wir uns nur was für firmware.* überlegen. Die Certs dafür müssen ja auch mind. 5 Server verteilt werden.

**Comment by belzebub40k** [comment]
Round Robin DNS verursacht noch ein ganz anders Problem.
https://community.letsencrypt.org/t/problem-with-round-robin-dns/13992

http-01 kommt somit schon mal nicht in frage und wir müssten auf dns-01 als challenge response setzen. Die einfachste Lösung wäre aber auf Round Robin DNS zu verzichten und Pudding zum externen Firmware-Server zu machen.

**Comment by kokel** [comment]
Oh, klingt logisch. Wir driften glaube ich ab ;-). Wir sollten das Thema hier auf die Agenda vom Admin-/Web-Team Treffen setzen.

**Comment by ka-ba** [comment]
@belzebub40k 
An dieser Stelle habt Ihr mich verloren :( . Was spricht denn dagegen, das identische cert für firmware.ff... auf mehreren virtual hosts zu verwenden? Oder - for that matter - gleich ein wildcard cert *.ff.... ?
@kokel 
Ja, da sollten wir das wohl besprechen...

**Comment by belzebub40k** [comment]
@ka-ba Letsencrypt tauscht standardmäßig über http Informationen aus um zu verifizieren ob man Inhaber der Domain ist. Wenn Letsencrypt aber immer auf einem anderen Server ankommt schlägt der Austausch der Daten fehl weil der Prozess der auf die Antwort wartet nicht auf diesem läuft.

**Comment by kokel** [comment]
@ka-ba da spricht nichts gegen, aber 1. was @belzebub40k sagt und 2. erlaubt LE keine wildcard certs ...

**Comment by ka-ba** [comment]
OK, habe gerade über deren Minigültigkeitszeiträume gelernt.
Das kann man ja manuell nicht handeln! Auf der anderen Seite wäre ich nicht begeistert, überall deren script-Geraffel installiert zu haben. Zum Einen muss auch das wieder gepflegt werden, zum Anderen ist das ein Sicherheitskritischer Bereich (per.Def.) und da ist mir bei dem Haufen scripts mit unbekannten Sicherheitslücken nicht wirklich wohl.
Vielleicht ist dann L.E. doch nicht das richtige?

**Comment by belzebub40k** [comment]
Pflege ist nicht notwendig nachdem es erstmal eingerichtet ist und sowohl Certbot (offizieller Client ursprünglich entwickelt von Letsencrypt und jetzt von der EFF gepflegt) als auch dehydrated (letsencrypt.sh) sind in den Debian Repositories enthalten und bleiben somit automatisch auf dem aktuellen Stand.

Sicherheitslücken sind natürlich nie auszuschließen da diese aber nur wenige Sekunde alle paar Tage ausgeführt werden sehe ich dies nicht als so kritisch an. Zumal Letsencrypt mittlerweile sehr verbreitet ist und auch von vielen Hostinganbietern eingesetzt wird.

Alternativ könnte man sich basieren auf [letsencrypt-nosudo](https://github.com/diafygi/letsencrypt-nosudo) etwas eigenes bauen was an zentraler Stelle (eigene VM/Container) unsere Zertifikate erzeugt und diese auf die nötigen Hosts verteilt.

**Comment by belzebub40k** [comment]
StartSSL wird eventuell in Zukunft keine Alternative mehr sein: http://www.golem.de/news/zertifikate-mozilla-will-startcom-und-wosign-das-vertrauen-entziehen-1609-123462.html

**Comment by belzebub40k** [comment]
Mozilla macht Ernst mit dem Rauswurf. Ab Firefox 51 sind Sartcom (und Wosign) keine vertrauenswürdigen CAs mehr. Firefox 51 ist für Januar nächsten Jahres geplant.

http://www.golem.de/news/wosign-und-startcom-mozilla-macht-ernst-mit-dem-rauswurf-1610-123829.html

**Comment by MAGICCC** [comment]
Da es gestern ein kleinen Meinungsaustausch von LE gab, wollte ich schnell niederschreiben, wie ich Cerbot benutze:

Ich erstelle im Webverzeichnis ein ```.well.known``` Ordner, um die Zertifikate via .well-known Request zu bekommen. Dabei kommt folgendes in die NGinx Config im :80 Block:
```
location ^~ /.well-known/ {
	alias /var/www/letsencrypt/.well-known/;
	allow all;
}
```

Damit ich die Zertifikate das Erste Mal requesten kann bzw. weitere (Sub)Domains hinzufügen kann, benutze ich einfach ein Script, welches aus einer Textdatei die Domains ausließt:
```
#!/bin/bash

BASEPATH="/root/letsencrypt/domain.tld"
CONFIG="$BASEPATH/cli.ini"
EMAIL="letsencrypt@domain.tld"
DOMAINS=""

while read line
do
        DOMAINS+="-d $line "
done < "$BASEPATH/domains.txt"

certbot certonly --email $EMAIL $DOMAINS --config $CONFIG
```

config.ini
```
rsa-key-size = 4096
authenticator = webroot
webroot-path = /var/www/letsencrypt
```

Als Cronjob benutze ich ein einfach ```@daily```:
```@daily /usr/bin/letsencrypt renew && /usr/sbin/service nginx reload```

**Comment by MAGICCC** [comment]
Meanwhile http://www.golem.de/news/zertifikate-auch-google-wirft-wosign-und-startcom-raus-1611-124162.html

**Comment by Maesto** [comment]
Also ich kann ja mal sagen wie ich es für milchreis.freifunk-mwu.de gelößt habe:
Der steht mit seinem v4 bein hinter meinem Reverse proxy. Weswegen ich SSL schon dort terminieren muss. Bei der Wartung von web.igeh.me (der proxy) hab ich alle seiten auf ssl updated.

web.igeh.me macht also per cron ein letsencrypt cert und schiebt das per rsync auf milchreis für sein v6.
Mein vorschlag:
Aktuell migrieren wir alles auf ansible. Mit einer ansible role die letsencrypt (wie auch immer) managed könnte sich schlicht jeder host seine certs besorgen, und so proxy probleme wie milchreis lassen sich trozdem weiterhin lösen.

**Comment by belzebub40k** [comment]
@prisma01 Ist zum dem Thema noch was offen oder können wir das Ticket schließen?

**Comment by prisma01** [comment]
Let's enctrypt ist jetzt ausgerollt, die Firmware ist auch per SSL runterladbar. Ich habe auch dehydrated verwendet, weil mir certbot zu fett war...
Wir haben für fast alle Seiten SSL only konfiguriert (mittels Redirect permanent), wir schicken einen HSTS header und unser Rating bei ssllabs ist gut. Die Firmware wir auf SSL oder http aussgeliefert, da die Nodes keine SSL library haben (zu wenig speicher). Das wird also so bleiben.
Ich erstelle gerade die Doku im Wiki, wenn das durch ich, schließe ich hier...

**Comment by prisma01** [comment]
Doku unter: https://wiki.freifunk-mwu.de/index.php/Howto/SSL_Zertifikate_mit_Let's_Encrypt
