### ISSUE TITLE
internen DNS Master auf Aubergine umziehen

### ISSUE THREAD

**Issue by kokel** [freifunk-mwu/technik-meta#31]
**Vorschlag:** Wir ziehen den DNS Master vom Spinat auf die Aubergine um

**Problem/ Auslöser:**
 * alfred2zone script läuft momentan auf dem Spinat, weil dieser DNS Master ist. 
 * Spinat ist Alfred Slave, bedeutet dass es irgendwann dazu kommt, dass der Spinat nicht alle Alfred Datensätze kennt
 * Aubergine ist Alfred Master aufgrund der Karten Scripte
 * Momentan lässt sich nur ein Alfred Master betreiben, Multi-Master ist aktuell noch broken: http://www.open-mesh.org/issues/202

**Vorteile:**
 * Gateway Konfiguration wird vereinheitlicht
 * Alle Scripte, die Alfred Daten auswerten laufen auf einer Kiste (Ja, SPOF, aber durch das Multi-Master Problem in Alfred aktuell leider nicht anders möglich)

Was denkt ihr? Falls angenommen werde ich mich um die Umsetzung kümmern.

**Comment by ka-ba** [comment]
Kokel, hilf mir bitte noch mal ganz kurz: Aubergine, Linse und Lotuswurzel sind allesamt VMs auf dem selben Blech?
alfred2zone ist das Ding, das die .users.. domains befüllt? (BTW: Hat das Teil ein Groß-/kleinschreibungsproblem?)
Haben wir für ffwi.org&ffmz.org eigentlich auch ein hidden-primary-setup? Oder werden wir das dann haben?

Was wären die Schritte?
- bind installieren
- bind als master konfigurieren
- das alfred-Zeugs an den Start bringen
- wenn Alles ordentlich tut, umschalten
- Aubergine zum slave machen

Prinzipiell finde ich den Vorschlag gut. Ich sehe eigentlich keine Nachteile.

SPOF? Es sind ja keine zeitkritischen Dinge über die wir hier reden. Wenn der hidden primary und die map mal 'ne Zeit weg sind, stribt das Netz nicht. Bei einem GAU hätten wir IMHO sogar problemfrei Zeit, die Kiste neu aufzusetzen.

**Comment by kokel** [comment]
Ich habe mal den Titel angepasst, lass uns erstmal nur DNS beleuchten. Aubergine ist schon länger alleiniger Alfred Master. 

* Ja, Lotuswurzel, Linse und Aubergine sind allesamt auf demselben Blech.
 * alfred2zone ist das Script, das *.nodes.ff[mz|wi].org befüllt. Groß-/Klein-Schwäche? Das befüllt die Zones 1:1. Der Knoten "Stalemate" heißt dann "Stalemate.nodes.ffwi.org". Dem DNS ist die Groß-/Kleinschreibung jedoch egal, also sollte alles grün sein.
 * Aktuell haben wir kein Hidden-Primary-Setup. Guter Punkt, das ist zwar nicht zwingend notwendig, würde aber Sinn machen.

Schritte auf Aubergine:
 * Bind installieren
 * Konfigurieren
 * Zonen umziehen

Schritte auf Spinat:
 * Bind Config identisch zu anderen Gates machen

Schritte auf anderen Gates:
 * Master für Slave Zonen umkonfigurieren

SPOF? Ja du hast Recht, keine netzkritischen Sachen. Die Slaves rennen 41 Tage ohne Master brav weiter.

**Comment by kokel** [comment]
Da es bisher keine Gegenstimmen gab, werde ich die Umkonfiguration bei Zeiten in Angriff nehmen.

**Comment by kokel** [comment]
Der Umzug des DNS Masters vom Spinat auf die Aubergine wurde vollzogen. Ebenso die Migration in ein Hidden Primary Setup.

- [X] BIND auf Aubergine installiert + konfiguriert
- [X] Benötigte Backend Scripts auf Aubergine aktiviert (BIND_CHECK + ICVPN Zone Generierung)
- [X] Zones migriert
- [X] SOA Record aller Zones angepasst
- [X] BIND auf Spinat in Slave Config umgewandelt
- [X] Slave Config restlicher Gates angepasst
- [X] gluon-gateway-doku aktualisiert
- [X] technik-meta Wiki aktualisiert

**Comment by kokel** [comment]
So, es ist nun alles abgeschlossen. Auch das alfred2zone script macht nun keine Probleme mehr.
