### ISSUE TITLE
Ubuntu-DHCPd-Bug in Gateway-Doku erwähnen?

### ISSUE THREAD

**Issue by yayachiken** [freifunk-mwu/technik-meta#38]
Hallo zusammen,

wir sind letztens beinahe böse von einem Bug beim dhcpd, der wohl spezifisch nur auf Ubuntu existiert, gebissen worden.

Obwohl der dhcpd normalerweise jede Stunde seine Lease-File aufräumen soll, wird durch ein anscheinend übermäßig restriktives AppArmor-Profil der nötige Dateizugriff unterbunden. [Hier ist der relevante Bugreport](https://bugs.launchpad.net/ubuntu/+source/isc-dhcp/+bug/1186662), leider ist nicht absehbar wann das gefixt wird, da ISC und Ubuntu sich gegenseitig den Schwarzen Peter zuschieben.

Jedenfalls führt der Bug dazu, dass alle MAC-Adressen gespeichert werden, die jemals eine IP-Adresse angefordert haben. Je nachdem ob man die MAC-Adresse schon als persönliches Datum auffasst, würde diese Datensammlung nach 7 Tagen illegal werden (Disclaimer: Bin natürlich kein Anwalt). Selbst wenn das aber nicht so ist, dann wäre die Datenspeicherung immer noch unnötig und sollte daher im Freifunk vermieden werden. Uns ist es nach ein paar Tagen zum Glück rechtzeitig aufgefallen, weil das Lease-File so merkwürdig groß geworden war.

Als Workaround starten wir im Moment alle 24 Stunden den dhcpd nachts neu, da er beim Neustart vor dem Privilegien droppen seine Lease-File ordentlich aufräumen kann und das auch tut. Verfallene Leases werden also maximal 24 Stunden gespeichert. Die "Downtime" beträgt wenige Sekunden. Wer sowieso schon eine IPv4 hat merkt nichts, wer gerade eine anfordert, wartet ein paar Sekunden länger.

Aufgrund der Gefahr, dass unabsichtlich fremde Daten unnötig gespeichert werden, würde ich vorschlagen, einen Hinweis auf diesen Bug beim [Absatz zu dhcpd](https://gluon-gateway-doku.readthedocs.org/de/latest/configuration/daemons/ddi.html#dhcpd) anzubringen, und auf den Workaround mit dem regelmäßigen Neustart zu verweisen.

Und wenn ihr schon dabei seid:
> Aus dem Netzplan wird sich eine Rage gezogen.

Es muss natürlich "Range" heißen :)

Gruß
David vom Freifunk Aachen

P.S.: Ich weiß, ich muss das "DOKU" Label hier anbringen, aber ich finde grade irgendwie nicht raus, wie das gehen soll. Sorry!

**Comment by spookey** [comment]
Hallo,
vielen Dank für den Hinweis!

Habe eben händisch auf der Lotuswurzel den dhcpd neu gestartet, das `/var/lib/dhcpd.leases` file schrumpfte von satten 5.6 M auf 520 K..

Für heute Abend ist ein Admin-Treffen angesetzt - werden in großer Runde nochmal darüber sprechen.

**Comment by ka-ba** [comment]
Da wir ganz zufällig gerade unsere besondere beta-Konfiguration laufen haben: wollen wir in diesem beta-Kontext testen, ob die Auswirkungen auf die clients tatsächlich so sind. wie erwartet?
Auf den neuen Gates könnten wir für einen solchen Test ganz aggressiv restarten - alle 5 oder 10 Minuten. Dann sollte das Verhalten beobachtbar werden.

**Comment by kokel** [comment]
@yayachiken Auch von mir danke für diesen wertvollen Hinweis!

Statt den DHCP daemon zyklisch neu zu starten schlage ich für uns vor die ACL-Variante zu testen.

**Comment by kokel** [comment]
So, ich habe die ACL-Variante auf der Lotuswurzel getestet und war erfolgreich.
Man muss lediglich das Paket ```acl``` installieren. Die mount-option "acl" ist in trusty bzw. ext4 schon default.

```
apt-get install acl

service isc-dhcp-server stop
setfacl -dm u:dhcpd:rwx /var/lib/dhcp
setfacl -m u:dhcpd:rwx /var/lib/dhcp
service isc-dhcp-server start
```

Fertig ...
