### ISSUE TITLE
Wasserfloh löst ffwi.org (für ffmz clients) nicht auf

### ISSUE THREAD

**Issue by ka-ba** [freifunk-mwu/technik-meta#39]
Sorry, hab grad nicht die Ruhe, selbst zu schauen, deshalb als issue hier erfasst.
Wolfgang:
-----------------------------------------------------
[... http://flugzeug.user.ffwi.org:8080/ ... ]
schade, dass der Zugriff von MZ aus nicht möglich ist. Zumindest bei mir.
![image](https://cloud.githubusercontent.com/assets/2435567/8508700/d08bad86-227a-11e5-95f2-fa364a9835e3.png)
-----------------------------------------------------

Vielleicht auch auf anderen Gates?

**Comment by whallmann** [comment]
Habe jetzt eine Verbindung hier zur Lotuswurzel.ffmz  Die kann ein NSlookup auf spinat.ffwi.org auflösen, aber nicht die anderen namen wie flugzeug und radio. Vielleicht hilft das beim Einkreisen

**Comment by kokel** [comment]
Das Problem existierte meines Wissens nach nur auf dem Wasserfloh. Habe das Zone-File dort gelöscht, nach einem BIND restart wurde die zone dann neu geholt und angelegt.

**Comment by ca-haddock** [comment]
passt nun auf allen Gates:

for I in 208 231 7 23 ; do echo $I ; dig +short flugzeug.user.ffwi.org @10.56.0.$I ; done
208
10.56.4.23
231
10.56.4.23
7
10.56.4.23
23
10.56.4.23

**Comment by ka-ba** [comment]
aus Mainz bestätigt:
user@client:~$ for I in 208 231 7 23 ; do echo $I ; dig +short flugzeug.user.ffwi.org @10.37.0.$I ; done
208
10.56.4.23
231
10.56.4.23
7
10.56.4.23
23
10.56.4.23
user@client:~$ nslookup flugzeug.user.ffwi.org
Server:		127.0.1.1
Address:	127.0.1.1#53

Name:	flugzeug.user.ffwi.org
Address: 10.56.4.23
