### ISSUE TITLE
Festplattenerweiterung Pudding

### ISSUE THREAD

**Issue by kokel** [freifunk-mwu/technik-meta#40]
Der Pudding hat momentan eine HDD-Kapazität von 80GB.

Während eines Build-Prozesses laufen diese nahezu komplett voll. In kurzer Zeit werden wir in Probleme laufen.

Die Festplatte muss also erweitert werden. Idealerweise um Luft für längere Zeit zu haben sind ca. 100GB zusätzlich erforderlich. Falls das zu viel für den Spender ist, würden 50GB auch erstmal viel helfen.

**Comment by juventas** [comment]
Wollt ihr Geld für eine neue Platte oder reicht eine gebrauchte? Ich hätte hier 2x 80GB 3,5"-SATA (nicht baugleich) und 1x 200GB 2,5"-SATA abzugeben. Die würde ich dann nochmal einem kurzen Stresstest unterziehen, weil die schon eine Weile nicht mehr im Einsatz sind.

**Comment by kokel** [comment]
Danke @juventas für das super Angebot, der Server ist aber eine private Spende (vServer auf privatem Host). Da wird das etwas schwierig :wink:

**Comment by ka-ba** [comment]
Kokel, was heißt "schwierig" konkret - im Hinblick auf folgende Frage: Wo steht der Host tatsächlich physisch? Steht der privat, oder steht er in einem Miet-RZ? Also: willst Du sagen, dass wir selbst keine Platten anklemmen können? (Denn ansonsten wäre das Angebot ja super und hilfreich!) Oder meinst Du andere Schwierigkeiten?

**Comment by kokel** [comment]
@ka-ba Das ist eine virtuelle Maschine auf einem Root-Server bei Hetzner meines Wissens nach. HDD wird vermutlich nicht das Problem sein. Es muss nur jemand den netten Spender mal anschreiben, dass die Platte in der VM erweitert wird.

@Maesto Wäre das möglich? hast du noch etwas HDD für uns übrig?

**Comment by Maesto** [comment]
Habt jetzt noch eine 100G Platte zusätzlich. Einfach zur VolumeGroup hinzufügen und das logische volume erweitern.

**Comment by kokel** [comment]
@Maesto LV ist schon erweitert ... Herzlichen Dank!

**Comment by spookey** [comment]
Schick, wie die Kurve da eine Stufe nach unten macht: 
http://pudding.freifunk-mwu.de/monitorix-cgi/monitorix.cgi?mode=localhost&graph=_fs01&when=1week&color=black

Vielen Dank :turtle:
