### ISSUE TITLE
v4-Routing aus Mz nach Wi geht nicht?

### ISSUE THREAD

**Issue by ka-ba** [freifunk-mwu/technik-meta#41]
Kann von einem Mainzer client z.B. aubergine.ffwi.org nicht erreichen (schon aber aubergine.ffmz.org) :

```
kaba@straylight:~/.ssh$ tracepath aubergine.ffwi.org
 1?: [LOCALHOST]                                         pmtu 1350
 1:  lotuswurzel.ffmz.org                                 23.095ms 
 1:  lotuswurzel.ffmz.org                                 32.149ms 
 2:  no reply
 3:  no reply
```

Die Lotuswurzel selbst kommt aber sehr wohl zur aubergine.ffwi.org :

```
[admin@lotuswurzel ~] traceroute aubergine.ffwi.org
traceroute to aubergine.ffwi.org (10.56.1.3), 30 hops max, 60 byte packets
 1  aubergine.ffwi.org (10.56.1.3)  276.092 ms  266.135 ms  266.142 ms
```

Das selbe Verhalten hatte ich gestern auch mit dem Wasserfloh als default gate.

Steh grad auf dem Schlauch und finde die Ursache nicht.

(Möglicherweise ist ICVPN-routing auch betroffen?)

**Comment by kokel** [comment]
Hallo @ka-ba 

```net.ipv4.conf.all.rp_filter = 0``` war auf der aubergine nicht gesetzt. Habe das nachgezogen.
Problem ist gefixt.

**Comment by ka-ba** [comment]
O ha! Auf was man da alles achten muss.
OK, wenigstens nachvollzogen: aubergine ist (auch) multi-homed; sie bekommt ein Mz-Päckchen an der Wi-Pforte -> Problem für überempfindlichen kernel. :/
Tut jetzt wunderbar. Kokel: mny thnx!
