### ISSUE TITLE
routing re-design auf alle Gates übernehmen

### ISSUE THREAD

**Issue by ka-ba** [freifunk-mwu/technik-meta#42]
re-design wurde auf Lotuswurzel getestet und für gut befunden (Admintreffen 150825); ist schon vollständig dokumentiert
Soll nun so auch auf die anderen Gates ausgerollt werden.
Hinweis: Auch Anpassungen in bird config geachten und übernehmen.

- [x] Spinat
- [x] Kaschu
- [x] Wasserfloh

**Comment by ka-ba** [comment]
... ist auch schon sauber dokumentiert: http://gluon-gateway-doku.readthedocs.org/de/latest/configuration/policyrouting.html
Ich mach mich endlich mal dran ...

**Comment by ka-ba** [comment]
Wasserfloh erledigt (hopefully Alles richtig ^^ )

**Comment by ka-ba** [comment]
So, durch.
Vielleicht kann aber jemand noch stichprobenmäßig mal durchschauen?
Ansonsten von dieser Front: go für RL :)

**Comment by spookey** [comment]
:thumbsup:
