### ISSUE TITLE
Dienst-Server bekommen ICVPN-Integration -> iBGP o.ä.

### ISSUE THREAD

**Issue by ka-ba** [freifunk-mwu/technik-meta#43]
Einige interne Dienste sollen aus ICVPN erreichbar sein. Dafür brauchen die entsprechenden (der entsprechende?) Server routes ins ICVPN. Dafür müssen sie an einem routing protocol mit den gates teilnehmen.

- [x] Aubergine (Karten)

**Comment by ka-ba** [comment]
So, fertig.
Großen Dank @kokel für den bugfix.
@kokel: Hast Du einen Kontakt in einer anderen community, der nun mal beide interne Karten testen könnte?

**Comment by kokel** [comment]
@ka-ba Sieht gut aus!

Funktioniert auch:
```
root@aubergine:~# ip r get fdca:ffee:ffda::1 from fd56:b4dc:4b1e::a38:103 oif wiBR
fdca:ffee:ffda::1 from fd56:b4dc:4b1e::a38:103 via fd56:b4dc:4b1e::a38:17 dev wiBR  src fd56:b4dc:4b1e::a38:103  metric 0 
    cache

root@aubergine:~# ip r get 10.223.0.1 from 10.56.1.3 oif wiBR
10.223.0.1 from 10.56.1.3 via 10.56.0.23 dev wiBR 
    cache
```

**Comment by ka-ba** [comment]
na denn :)
