### ISSUE TITLE
Domain ffmwu.org in Betrieb nehmen (war: einkaufen)

### ISSUE THREAD

**Issue by backstube** [freifunk-mwu/technik-meta#45]
für verschiedene Sachen, die nicht stadtfokussiert sind, wäre eine übergreifende Domain gut. Die o.g. ist auch noch frei, kostet bei zB. inwx.de 15 € pro Jahr. Eine .de kostet zum Vergleich ca. 6 € im Jahr.

**Comment by juventas** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Es gibt doch bereits freifunk-mwu.de

Am 15.09.2015 um 16:08 schrieb backstube:
> für verschiedene Sachen, die nicht stadtfokussiert sind, wäre eine 
> übergreifende Domain gut. Die o.g. ist auch noch frei, kostet bei
> zB. inwx.de 15 € pro Jahr. Eine .de kostet zum Vergleich ca. 6 € im
> Jahr.
> 
> — Reply to this email directly or view it on GitHub 
> <https://github.com/freifunk-mwu/technik-meta/issues/45>.
> 
-----BEGIN PGP SIGNATURE-----

iQIcBAEBCgAGBQJV+CfzAAoJEARntQxeJCQeptMP/0VH2g0mp/WnT9np+QLsiXtF
MtNBgRiaVEjhMex2WYB3v22+GJ8ZqOiyphttUg5UJfGhyCH4fkm23+Cx80N1Djyy
lA6FGZ/UgjjxMXd+tyS6osQT9CeVbJl8V71UDpcl1zEBGbvM6SDu1xinfPBC0DJb
DAfQS5esl99fLklMWGJkK0VoVYh6CV8qpi1AasJMyKe/YX97JVb4R712bbrKNBKF
rQOV77p7YhijdAp7OT2qvGHgX6Prvh6P7fK6eirHroF73mIfUc6eq6U1hr9f7vok
NAF7Ofag7eNAWES4VHRH3+CNBvN2wI4kl61h+dq4ahz2UspC/1MC2VWTBoDxyQZ2
14LMck8xf419m1FuJRqJgiB7yJx2403OtS2am318sddoad+WKvgaEnbKlA2dNElD
zHMU/K0eatG+ulyl+b/Pj7dKRB6P71BUL02zAxyLJevr/go7Ab4FHTR3DeSw1948
v+M/ETILpdTSYzKyHuCyPsSWW2iRBWoOl7GVfn0v631JUKXAyLKf7netft9HN4nO
XZPnbalXfrW+WngqucR/sr6sy49zwyYd41BPBEKpZEyJyA3/stWv9sRn0JNIeUKj
0OObR2ND4AB25ubvgD3P7Cub72CA3r0tM4eJ1D8CbNq816GM6sTyJTTzZdg8zWrP
33oXQcTnroOTqoBw9qgC
=Yy+D
-----END PGP SIGNATURE-----

**Comment by backstube** [comment]
jo, die ffwmu.org ist aber kürzer und schicker und konsistent zu ffmz.org und ffwi.org und ffbin.org.
Wobei letztere wollen die Binger erst noch holen, die ist noch frei zZt.

**Comment by kokel** [comment]
Ich bin auch pro ffmwu.org. Das ist kürzer als freifunk-mwu.de. Wenn wir freifunk-mwu.de verwenden wollten müssten wir auch erstmal ein Split-Horizon DNS aufsetzen. Das müsste aber eh mal gemacht werden.

Die Domain sollte dann unser lokale Domain Dealer registrieren, der das für unsere anderen Domains auch gemacht hat.

**Comment by spookey** [comment]
Wenn das für Notwendig erachtet wird, und wir uns das Leisten könen - gerne! 

Wollen wir das genauso halten wie unsere bisherige Policy?
Die freifunk-*.de Domains um extern im Internet erreichbar zu sein, 
die ff*.org Domains nur intern im Freifunk Netz schalten?

Oder was genau ist der konkrete Anwendungsfall?

**Comment by backstube** [comment]
Das ist die Policy, die ich auch kenne und mag. Und hier fehlt ffmwu.org noch, die dem bisherigen Schema folgt, wenn es eben um community-übergreifende Sachen geht. Wo wir mMn generell hinstreben sollten, fort von dem Kleinklein ffmz und ffwi. 

Wobei mir in dieser (und auch vorigen) Diskussionen nicht einleuchtet(e), warum wir intern, innerhalb unseres Intranets, nicht einfach eigene TLD vergeben: fliegertracker.ff   webradio.ff
Das mache ich hier im LAN auch, auch mit Split-Horizon-DNS.
Wieso es mal zum Kaufen der kurzen ffxy.orgs kam, ist mir schleierhaft.

**Comment by juventas** [comment]
Ich halte von erfundenen TLDs nichts. Das führt spätestens dann zu
Problemen, wenn es die auch im richtigen Leben gibt.

Am 15.09.2015 um 18:55 schrieb backstube:
> Das ist die Policy, die ich auch kenne und mag. Und hier fehlt ffmwu.org
> noch, die dem bisherigen Schema folgt, wenn es eben um
> community-übergreifende Sachen geht. Wo wir mMn generell hinstreben
> sollten, fort von dem Kleinklein ffmz und ffwi.
> 
> Wobei mir in dieser (und auch vorigen) Diskussionen nicht
> einleuchtet(e), warum wir intern, innerhalb unseres Intranets, nicht
> einfach eigene TLD vergeben: fliegertracker.ff webradio.ff
> Das mache ich hier im LAN auch, auch mit Split-Horizon-DNS.
> Wieso es mal zum Kaufen der kurzen ffxy.orgs kam, ist mir schleierhaft.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freifunk-mwu/technik-meta/issues/45#issuecomment-140461665>.
> 

-- 
PGP-Fingerprint: 51E8 B818 EE1B D858 D8E6 CA48 0467 B50C 5E24 241E

**Comment by backstube** [comment]
Erstens dringen die nicht nach draußen. Zweitens gibt es .ff draußen nicht. Ist keine ccTLD und auch keine generische.

**Comment by kokel** [comment]
Wir schweifen ab. Der Vollständigkeit halber warum wir offizielle TLDs genommen haben:

* keine Überschneidung falls es die irgendwann doch geben sollte
* Primäres Argument war, dass man nur auf offizielle TLDs Zertifikate von z.B. CAcert austellen lassen kann

@spookey Der Anwendungsfall für Split-Horizon DNS ist:
Mal angenommen wir hätten endlich all unsere Dienste im Freifunk-Netz, dann könnten wir z.B. für www.freifunk-mainz.de + wiesbaden.freifunk.net interne Freifunk-IPs rausgeben. Ansonsten würde der Zugriff auf die Websites aufgrund öffentlicher IP über ein Gate durchs Exit-VPN, durchs Internet und wieder zurück zu einem Server, der sowieso schon im FF-Netz hängt, verlaufen.

**Comment by juventas** [comment]
Nur weil es sie noch nicht gibt heißt das nicht, daß es sie nie geben
wird. Ich bleibe daher bei meiner Meinung: Ich würde keine erfundenen
TLDs verwenden.

Am 15.09.2015 um 19:04 schrieb backstube:
> Erstens dringen die nicht nach draußen. Zweitens gibt es .ff draußen
> nicht. Ist keine ccTLD und auch keine generische.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freifunk-mwu/technik-meta/issues/45#issuecomment-140463713>.
> 

-- 
PGP-Fingerprint: 51E8 B818 EE1B D858 D8E6 CA48 0467 B50C 5E24 241E

**Comment by spookey** [comment]
Das hat einen einfachen Grund:
In Zeiten von TLDs wie z.B. ``.app``, ``.haus``, ``.meme``, ``.money``, ``.schule``, ``.sucks``, ``.pink`` und weiteren eskapaden, kann es sein, dass irgendwann die TLD ``.ff`` aktiviert wird.
Dann hat man das Problem, dass man nichtmehr zwischen seinem eigenen Dienst im FF-Netz, und einem externen Dienst unterscheiden kann..

So wie wir das jetzt machen (intern eine Domain schalten, die auch weltweit existiert) ist die sauberste Lösung, alles andere funktioniert zwar, ist aber Pfusch!

**Comment by ka-ba** [comment]
Bevor jemand unnötig Geld in die Hand nimmt: war der erste Punkt von Kokel angekommen? "Die Domain sollte dann unser lokale Domain Dealer registrieren, der das für unsere anderen Domains auch gemacht hat."

**Comment by spookey** [comment]
*bump* Wie ist denn hier der Stand?

**Comment by ka-ba** [comment]
Hab den Dealer grad mal nach Preisen gefragt.
Ich lese oben raus, dass wir groben Konsens haben, sie im Zweifel mal zu reservieren!?

**Comment by ka-ba** [comment]
Wir haben mal wieder eine domain geschenkt bekommen:
```
~$ whois ffmwu.org | egrep 'Registrant Name|^Domain'
Domain Name:FFMWU.ORG
Domain ID: D177949326-LROR
Domain Status: serverTransferProhibited -- http://www.icann.org/epp#serverTransferProhibited
Domain Status: addPeriod -- http://www.icann.org/epp#addPeriod
Registrant Name:Freifunk MWU Admins
```
Nu müssen wir sie noch füllen.

**Comment by ka-ba** [comment]
@kokel: Was den schizophrenen DNS angeht: aus dem Bauch würde ich eher die kurze domain am Horizont spalten, nicht die lange. In der langen können wir für die entscheidenden services dann CNAMEs auf die kurze einfügen.
Mir wäre es lieber, die kurze nach draußen zu bringen, als die lange nach drinnen.

**Comment by kokel** [comment]
@ka-ba Meiner Meinung nach macht es nur Sinn, wenn wir alle Domains splitten.
Wir haben nichts gewonnen, wenn wir die kurzen nach draußen bringen und von den langen CNAMEn. Das würde nur funktionieren, wenn wir alle unsere URLs auf die kurzen bringen.

Das Ziel des Split-Horizon DNS ist ja, dass wir all unsere Dienste unter derselben URL auch innerhalb des Freifunk-Netzes erreichbar machen. Nach außen mit den Public Adressen, intern mit den Mesh-Adressen.

Meiner Meinung nach ist es auch am saubersten, wenn wir einfach alle splitten. Weniger komplexität, homogene config, etc.

Was sind denn die Gründe warum dir dein Bauch das so sagt?

**Comment by ka-ba** [comment]
Mein Bauch begründet seine Ratschläge nicht. ;)
Die kurzen wären mir irgendwie lieber als die langen. Aber bei _allen_ bin ich auch sofort dabei! (...beeinhaltet ja die kurzen...)

**Comment by kokel** [comment]
ffmwu.org ist ja nun in Betrieb. Deshalb schließe ich dieses Ticket. Für Split Horizon sollte dann ein neues Ticket (wenn nötig) eröffnet werden.
