### ISSUE TITLE
Neuer vServer

### ISSUE THREAD

**Issue by kokel** [freifunk-mwu/technik-meta#46]
Servus,

ein Freifunker möchte uns bzw. hat uns quasi schon ein VM gespendet. Es ist eine VM mit 4 vCPUs, 4GB Ram, 60GB HDD. Der steht bei online.net in Paris.

Nehmen wir die Spende an? Wenn ja, wofür verwenden wir diese?

Mir schwebt dieser Verwendungszweck vor:
- quasi jegliches Web-Zeugs (auch von Uberspace)
  - Homepage MZ+WI
- fast alles was auf der Aubergine läuft und nicht HDD hungrig ist:
  - Alfred Master
  - Intern DNS Master
  - Freifunk API Files
  - Karten!
  - Portale

Damit hätten wir den SPOF des Hetzner-Root-Server (Lotuswurzel, Aubergine, Linse) schonmal verringert.

Grüße,
Tobias

**Comment by backstube** [comment]
Klingt doch erstmal super. Für wie lange steht der denn zur Verfügung? 
Nicht, daß wir dorthin umziehen und 6 Mon. später das ganze Gelup wieder woanders hintun müssen ...

**Comment by juventas** [comment]
Den gleichen (kleinen) Einwand wollte ich auch gerade schreiben.
Ansonsten wüsste ich auch nicht, was dagegen sprechen sollte.

Am 15.09.2015 um 19:34 schrieb backstube:
> Klingt doch erstmal super. Für wie lange steht der denn zur Verfügung?
> Nicht, daß wir dorthin umziehen und 6 Mon. später das ganze Gelup wieder
> woanders hintun müssen ...
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/freifunk-mwu/technik-meta/issues/46#issuecomment-140474815>.
> 

-- 
PGP-Fingerprint: 51E8 B818 EE1B D858 D8E6 CA48 0467 B50C 5E24 241E

**Comment by MAGICCC** [comment]
Moin Jungs,
Ich bin der Spender, wollte mich grad mal melden.
Eine sehr spannende Frage ist dies aufjedenfall! Der Server kostet ja nur ca. 20€, und ich könnte immernoch VMs draufschmeissen, also müsste der Server eine längere Zeit verfügbar sein.
Vorteil ist halt die 1Gbit/s Anbindung und unlimited Traffic nach meiner Meinung nach

**Comment by backstube** [comment]
Hi Magiccc,
guter Mann! :)   Besten Dank für Deine Bereitschaft der Unterstützung.

Eine interessante Frage ist das ohne Frage ;)  Und wo Du gerade hier bist *und* der einzige bist, der sie beantworten kann: sach doch mal, wie lange denn so? ;-)

Daß der auch noch schnell angebunden ist und keiner auf den Zähler schaut, mach ihn ja nur noch leckererer :)

Viele Grüße!

**Comment by spookey** [comment]
Der Traffic ist wirklich unlimitiert? Dann böte sich eher ein Gateway als eine Dienste Maschine dafür an?

**Comment by MAGICCC** [comment]
>Eine interessante Frage ist das ohne Frage ;) Und wo Du gerade hier bist und der einzige bist, der sie beantworten kann: sach doch mal, wie lange denn so? ;-)
Aufjedenfall länger als 6 Monate :p 

>Der Traffic ist wirklich unlimitiert?
Laut Homepage ja, aber ich kenne Fälle wo User nach 30+TB pro Monat eine Nachricht bekommen haben, dass sie doch ihren Traffic runterschrauben sollen oder gerne upgraden sollten
Da bietet sich (http://www.lowendtalk.com/discussion/49410/online-net-guaranteed-bandwidth-server) [dieser] Artikel an, ist noch recht neu diese kleine Diskussion. (Zwar wegen der andauerden Überschreitung von der garantierten Bandbreite, aber das kann man 1:1 übernehmen)

**Comment by kokel** [comment]
Also wenn wir jetzt einfach ein Gate umziehen statt einen neuen Server zu nutzen, haben wir nicht viel gewonnen. Bei online.net Server klicken für Gates kann man (evtl. auch der Verein) immer noch.

**Comment by ka-ba** [comment]
@kokel, na ja, das ist nicht ganz richtig. Wir gewinnen den unlimited traffic (nach Diskussion ist's ja keiner, aber wenigstens ~30T). Wie viel traffic machen unsere Gates denn aktuell jeweils?
Auf die Maschine, auf der vorher das Gate war, können dann die von Dir vorgeschlagenen Services umziehen. Dann hätten wir einen Gesamtgewinn, oder nicht?
Da bliebe nur das Problem, dass der hdd space der neuen VM (vielen dank übrigens @MAGICCC !) etwas knapp für ein gate ist?

**Comment by MAGICCC** [comment]
>Da bliebe nur das Problem, dass der hdd space der neuen VM (vielen dank übrigens @MAGICCC !) etwas knapp für ein gate ist?
Kann auch ne 2te VM anlegen bzw. die jetzige HDD vergrößern. Wieviel PLatz braucht denn ein Gate ca?

**Comment by spookey** [comment]
Der Wasserfloh hat momentan ``12G`` belegt,
die Lotuswurzel ``14G``,
Spinat ``21G`` (wtf, why?!),
Kaschu hat ``2.3G`` mit dem System voll, die Firmware für die Nodes sind auf einer extra Partition mit ``20G`` belegt. 

Die Firmware ist also das, was so viel Speicher frisst.
Wir können uns überlegen ob wir mittelfristig die Firmware-Mirror von den Gateways entkoppeln, oder ob wir die Frequenz mit der wir Experimentals bauen leicht erhöhen...

**Comment by ca-haddock** [comment]
Hi  MAGICCC
"bau" einfach eine 2 platte für die Firmware ein. Hab ich auf Kaschu auch so gemacht. Dann brauch ein gateway > 3 GB.

**Comment by MAGICCC** [comment]
Habe ich was nun nicht kapiert oder warum reichen die 60GB nicht aus?
Selbst wenn aus irgendeinem Grund der Server 30GB belegt ist, sind immernoch knappe 30GB frei. Nicht falschverstehen, aber kommt mir grad ein wenig spanisch vor..
Mounten kann ich ja immer wieder Platten, 1TB physisch sind ja verbaut

**Comment by ca-haddock** [comment]
Ja 60 GB sollten reichen ;) 20€ sounds good was ist den das für ein Blech ?

**Comment by ca-haddock** [comment]
Was spricht gegen einen weiteres Gate ?

**Comment by MAGICCC** [comment]
>Ja 60 GB sollten reichen ;) 20€ sounds good was ist den das für ein Blech ?

Ist [dieser](http://www.online.net/en/dedicated-server/dedibox-xc) hier. Gammelt bei schon seit 1-2 Monaten nur rum, also warum nicht mal was zum arbeiten geben

**Comment by knirps99** [comment]
Ich hab mir das mal auf dem Spinat angeschaut

/var/www/html nehmen schon
    9.7GiB [##########] /firmware
    4.2GiB [####      ]  big_data_file
  172.0KiB [          ] /traffic
    8.0KiB [          ] /system
    8.0KiB [          ] /static
    4.0KiB [          ]  index.html

zu dem 4.2GiB big_data_file kommen noch 3,9Gib im apt-get cache die
firmware an sich sind knapp 10GiB plus ~ 2Gib System sind wir bei 21 ...
 hier sind allerdings auch zwei 500G Platten verbaut von daher kein
problem ...

Gruesse,
Moritz

**Comment by ka-ba** [comment]
Hi! Sorry, ich wollte nix anrichten :( Hatte irgendwie im Hinterkopf, jemand hätte die HDD-Größe angemerkt, selber grad keine Zeit, die Zahlen zu checken und wollte nur verhindern, dass ein wichtiger Aspekt in Vergessenheit gerät. War wohl eine falsche Erinnerung und Alles ist bestens! :)

@ca-haddock: wir hatten mal abgestimmt, die Anzahl der Gates nicht zu groß werden zu lassen. Irgendwann ist der Gewinn durch ein weiteres Gate nicht mehr groß, aber es muss auch aufgesetzt und gepflegt werden. Aktuell kommen wir mit vier ja gut hin, oder nicht?

**Comment by kokel** [comment]
Jo, 60G reichen für ein Gate aus. Die Lotuswurzel hat z.B. nur ne 50G Platte. Zur Firmware: Das hält sich echt in Grenzen, wenn man regelmäßig aufräumt und alte experimentals entweder von der _library nach _archive verschiebt oder einfach löscht. Da wäre ein Cronjob auch nicht verkehrt, der alte experimental älter als 10-15 Tage oder so automatisch löscht.

Ist der Konsens nun, dass ein vorhandenes Gate umgezogen wird?

Zum Thema zusätzliches Gate: ka-ba hats ja schon gesagt. Wir sollten zunächst bei den vier Gates bleiben, die sind auch noch lange nicht wirklich ausgelastet. Zum Vergleich: Hamburg mit knappen 900 Knoten und das doppelte an Clients hat 3-4 Gates. Die haben aber bestimmt einen besseren Internet-Durchsatz (direktes Peering). fastd-CPU-Belastung und Internet-Durchsatz in Verbindung mit Knoten- und Client-Anzahl sind meiner Meinung nach die beiden Parameter, die wir im Auge behalten sollten, um zu entscheiden ob ein weiteres Gate nötig ist, um die Internet-Bandbreite besser zu verteilen. Wenn wir auf den Knoten das fastd-peer-limit auf 1 reduzieren, geht die fastd-Last + Grundrauschen auch nochmal etwas runter.

**Comment by ca-haddock** [comment]
Hi
macht das sinn ein gate umzuziehen ? Wie sieht das mit dem Recht in Frankreich aus. In Frankreich wurde die Vorratsdatenspeicherung mit 12-monatiger Speicherung im Rahmen der Gesetze zur Terrorismusbekämpfung am 23. Januar 2006 eingeführt. Quelle Wikipedia.
Das mit der mangelden Redundanz bei Hetzner sehe ich entspannt. Wir stehen in unterschiedlichen RZ. Ok die Core Switches sind die gemeinsam aber das ist auch bein DECIX so. Dafür wird intergate Traffic nicht gezählt.Wenn sollten wir Spinat ablösen der macht a.t.m. die meiste Arbeit. Was den Aufwand angeht, sollten wir mal an Saltstack Chef... denken.Ich würde aber gerne erst mal den Anbieter testen. 20 € klingt supergünstig. Wer betreibt dass RZ der Mossad ? Nicht dass nach 2 Monaten mit 20 TB dass Licht ausgeht. Hatte so was mal in England. Gab auf einmal ständig probleme mit dem Server.

**Comment by spookey** [comment]
@ca-haddock:
Der Hinterschinken stand auch in Frankreich. Deshalb hatte ich damals auch drauf bestanden, dass wir unsere Config auf eventuelle Lecks abklopfen.

@kokel, @ka-ba:
Ein vorhandenes Gate umziehen scheint mir ebenfalls das Mittel der Wahl, diese Hardware ist zu gut, um einfach "nur" einen Dienste Server darauf zu betreiben.

Die Frage ist nur: Welches?
(Steche ich in ein Hornissennest, wenn ich das mit der durchschnittlich höchsten Downtime vorschlage? :heart_eyes_cat: )

**Comment by ca-haddock** [comment]
@spookey woher weist du wie gut die Hardware ist ? Hab ich da was verpasst ? Ich habe noch keine Specs vom blech gesehen.

**Comment by kokel** [comment]
@ca-haddock Specs: http://www.online.net/en/dedicated-server/dedibox-xc, RZ: http://www.iliad-datacenter.fr/
Gate umziehen macht Sinn, wenn wir bei vier Gates bleiben wollen und weil es nicht so aufwändig ist wie ein neues Gate hochzuziehen:
 * neuer ICVPN host: Dauert ewig bis die anderen Communities ihr Config updaten
 * müssten ein Firmware update machen

Aufgrund des begrenzten Traffics würde es natürlich Sinn machen den Spinat umzuziehen, aber hier nicht möglich, weil privater Server und nicht sinnvoll, weil der Umzug von Blech auf VM ein Rückschritt wär.
Die ursprüngliche Intention war den SPOF meines Hosts zu reduzieren (Lotuswurzel, Aubergine, Linse). Also wenn wir das Ding für ein Gate nutzen ist es aus meiner Sicht das sinnvollste die Lotuswurzel umzuziehen.

Der Verein soll sich mal Webtropia anschauen: https://www.webtropia.com/de/root-server/uebersicht/root-server-vergleich.html
Werben auch mit unlimited Traffic und hosten in http://www.myloc.de/rechenzentrum.html . FFDA hat sich grad den Root Server S geklickt.

**Comment by ca-haddock** [comment]
Hi Tobias,

dann lass uns doch bei der Idee bleiben deinen Host von Diensten zu befreien.Das mit dem rückschritt von Blech auf VM bei Spinat sehe ich nicht so.Mein ester umzugskandiat wäre die  Aubergine. Bei der Anfrage an Webtrobia solte der Verein kommunizieren das er viel Trafic macht. Ich bin bei Flat Angeboten etwas misstrauisch.

**Comment by MAGICCC** [comment]
Ja dann ziehen wir die Aubergine um, wenn das passt

**Comment by kokel** [comment]
Also sehe ich das richtig, dass alle damit einverstanden sind die Aubergine umzuziehen?

**Comment by ka-ba** [comment]
Geht da VM einpacken, kopieren, IP anpassen, wieder anwerfen?
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by kokel** [comment]
Ich denke nicht. Auf dem Host dieser neuen VM läuft VMware ESX? Die Aubergine ist ne KVM-basiert VM. Ich kann mich auch gerne um den Umzug kümmern.

**Comment by MAGICCC** [comment]
Man kann via VMWare Converter die KVM VM konvertieren und auf ESX umziehen. Muss ich mir mal anschauen.

**Comment by MAGICCC** [comment]
Kleines Update:
Wenn wir die VM konverten müssten wir sogut wie alles abschalten, was auf dem Server läuft um keine Probleme zu bekommen. Nachteil wäre hier natürlich eine Downtime von den Services zu erwarten.

**Comment by ka-ba** [comment]
"ping" :)
Wie ist denn hier grad der Stand?

**Comment by kokel** [comment]
@ka-ba Der Status ist noch unverändert. Weiß noch nicht wann ich dazu komme ;-)

**Comment by ka-ba** [comment]
Status aus letztem AdminTreffen: vServer ist aktiv, wir haben Zugriff, Umzug ist schon in Arbeit

**Comment by kokel** [comment]
Moin, ich wollte grad die Karten, Alfred Master und BIND Master auf die Zwiebel umziehen. Musste leider feststellen, dass die VM allein schon mit der Erzeugung eines Kartensatze überfordert ist, für Wiesbaden allein dauert ein Lauf ~2:30 Minuten 

```
admin@zwiebel:~$ time $HOME/clones/ffmap-backend-wi/mkmap-wi.sh
real	2m30.103s
user	2m7.412s
sys	0m21.944s
```

Wenn die anderen beiden Kartensätze dazukommen und dann minütlich laufen gibts einen Supergau. Müssen uns also etwas anderes überlegen.

**Comment by MAGICCC** [comment]
Hm, das ist natürlich suboptimal. Wäre es sinnvoll, wenn man die Kiste plattmacht und das ganze Blech benutzt und hoffen, dass das mit den 'real' Cores dann besser funktioniert?
Ist halt blöd, wenn man nochmal alles rüberschiebt.

**Comment by kokel** [comment]
Bei der CPU habe ich wenig Hoffnung, dass das trotzdem performt.

Alternativ können wir die RRD Statistiken einfach droppen, dann braucht ein Lauf nur noch $Sekunden.
Ich finde es legitim zu sagen die Statistiken können wir nicht mehr unterstützen weil zu ressourcenhungrid/performt nicht. $Jemand denkt sich was anderes zwecks Stats aus.

**Comment by MAGICCC** [comment]
Wir reden über die Clientsstats, die auf in data/nodes/ liegen oder? Falls ja, die würde ich ungern droppen.
Habe da 2 Ideen:
1.) Cronjobintervalle erhöhen
2.) Nur einmal Statistiken generien (MWU) und diese Bildchen dann in die 3 Karten einfügen. Haben halt mehr Speicherplatzverbrauch, dafür werden diese nur 1x generiert

**Comment by kokel** [comment]
1.) Müsste man zyklisch erhöhen, da immer mehr Knoten dazukommen.
2.) Meiner Meinung nach ein dirty Hack. Das machts nicht wiklich besser.

**Comment by MAGICCC** [comment]
Neue News?
Ich könnte den Server auch weghauen und bei netcup o.ä. einen holen und Freifunk MWU unterstützen. Besser als den Server idlen zu lassen und Strom zu fressen :)

**Comment by kokel** [comment]
Der Server kann leider für die Karte nicht verwendet werden, da zu wenig CPU Leistung.
Aktuell läuft dort ein Test-Setup für ein alternatives Monitoring (LibreNMS). Wenn du nichts dagegen hast würden wir den für Monitoring weiterverwenden.

**Comment by MAGICCC** [comment]
Ja, wie im IRC besprochen können wir das machen. Soll ich allerdings den Server reinstallieren, dann hat man als Hostsystem ein Ubuntu und kein ESXi. Mir es ist egal, da ich immer wieder Sachen an der VM ändern kann, wenn erwünscht

**Comment by kokel** [comment]
Die VM ist schon lange in Betrieb und wird fürs Monitoring verwendet. Issue wird geschlossen.
