### ISSUE TITLE
Label: 'Doku'

### ISSUE THREAD

**Issue by svenherford** [freifunk-mwu/technik-meta#47]
Hallo,
ich versuche ein Freifunk-Gateway für die Cummunity Herford aufzusetzen. 
Ich folge dazu der Anleitung auf https://gluon-gateway-doku.readthedocs.org/de/latest/configuration/daemons/exitvpn.html
Im Abschnitt FIREWALL komme ich immer zu einem Fehler: 
root@gw1:~# iptables -A POSTROUTING -s 10.37.0.0/18,10.56.0.0/18 -j MASQUERADE
iptables: No chain/target/match by that name.

Kann es sei, dass es stattdessen heißen muss:
root@gw1:~# iptables -t nat -A POSTROUTING -s 10.37.0.0/18,10.56.0.0/18 -j MASQUERADE

Vielen Dank für Eure Unterstützung
sven

**Comment by kokel** [comment]
Vielen Dank für den Hinweis. Das ist tatsächlich ein Fehler in unserer Doku, habe es grade gefixt.
Falls dir noch mehr Fehler auffallen sollten, immer her damit ;-)

**Comment by spookey** [comment]
Alles klar, ich mach hier mal zu.

Vielen Dank fürs melden, und vielen Dank fürs fixen!
