### ISSUE TITLE
Email Adressen Homepage

### ISSUE THREAD

**Issue by Klexx** [freifunk-mwu/technik-meta#48]
Moin,

wir sollten ggf. unsere Email Adressen auf unseren Homepages vor Bots schützen, um spam zu vermeiden. Beispielsweise auf freifunk-mainz.de.

Mögliche Lösungen.: https://www.hosteurope.de/blog/15-moeglichkeiten-die-e-mail-adresse-geschuetzt-darzustellen/

(Sollen Bugs der Homepage in dem Repo der Homepage oder hier behandelt werden ?)

**Comment by ka-ba** [comment]
unbedingte Zustimmung!

**Comment by ka-ba** [comment]
erledigt oder noch offen?

**Comment by Klexx** [comment]
dürfte noch offen sein

**Comment by prisma01** [comment]
Ich verwende für sowas seit Jahren den PHP Obfuscator https://github.com/Codingrecipes/PHPFormObfuscator
und ein Kontakt Formular....

**Comment by kokel** [comment]
Ist das noch aktuell bzw. wird daran gearbeitet?

**Comment by prisma01** [comment]
Gute Erinnerung. Ich sehe auf der FFMZ Homepage nur die kontakt@ Adresse. Haben wir irgendwo noch mehr, die Spam sicher gemacht werden müssten?
