### ISSUE TITLE
Newbie mit Angebot

### ISSUE THREAD

**Issue by volkerm81** [freifunk-mwu/technik-meta#49]
Hallo Freifunker.
Ganz kurze Vorstellung:
Volker, 34, meines Zeichens Sysadmin bei nem mittelständischen Unternehmen in WI. Habe bei mir zu Hause mittlerweile auch nen Knoten laufen und versuche das ganze zu Hause in Idstein auch ein wenig zu pushen.

Soviel zum Newbie und Vorstellung, jetzt zum Angebot.
Habe in der Firma den ein oder anderen alten Server rumliegen. Ältere HP-Kiste, Xeon Dual CPU, alle so mit rund 4GB RAM und recht flotten Platten.
Wir haben nen Internetanschluss von der Witcom ohne jegliche Volumenbegrenzung. Wie kann ich denn davon dem Netz was zur Verfügung stellen? Oder was wird benötigt? Oder wie kann man sich da einbringen?

**Comment by ka-ba** [comment]
Hups! Klingt doch interessant :)
Melde Dich doch vielleicht einfach mal auf der Admin-Liste, Da können wir vielleicht besser diskutieren? Das wäre admin an der domain freifunk-mainz (noch, gilt auch für Wi, zieht demnächst mal um) mit deutscher tld. Wir schreiben dann hoffentlich Cc an Dich zurück (hint, hint an die anderen admins, ans Cc zu denken ;) )

**Comment by volkerm81** [comment]
Als Mail an admin@ oder maschinenraum@ ? Euer Wiki verweist mich hier entweder hier an Github oder maschinenraum@ . 
Bei Admin steht, dass da keine Diskussionen geführt werden.
Wat nu? :D

**Comment by MichaelZiegler** [comment]
Bei maschinenraum@ bekommen es mehr Leute mit, die es wahrscheinlich auch interessant finden...

**Comment by ka-ba** [comment]
Wollen wir dieses issue schließen, wo sich die Diskussion damals tatsächlich in die maschinenraum-Liste verlagert hat?
Haben wir eigentlich das Angebot der server aus den Augen verloren, oder konnten wir dann doch keine sinnvolle Verwendung finden? (Karten-Zeugs???)

**Comment by belzebub40k** [comment]
Ich interpretiere das Schweigen mal als Zustimmung. Wenn es jemand anders sieht kann er das Ticket einfach wieder eröffnen.
